apiVersion: v1
kind: Service
metadata:
  name: simplecustomer-service
spec:
  selector:
    app: simplecustomer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
